name: Make Release

on:
  workflow_dispatch:

jobs:
  build_server_mfc:
    name: Build server-mfc
    runs-on: windows-latest
    defaults:
      run:
        working-directory: server-mfc
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
    steps:
      - uses: actions/checkout@v3
      - run: git pull
      - uses: microsoft/setup-msbuild@v1
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: e57b2167e66c847f991bd6bce1355b85acd944e8
      - run: vcpkg integrate install
      - run: vcpkg install asio protobuf spdlog[wchar] wil nlohmann-json
      - run: msbuild /m /p:Configuration=Release,Platform=x64
      - name: Checksum
        run: cd x64/Release/ && sha256sum *.exe | tee $(ls *.exe).sha256
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: server-mfc
          path: |
            server-mfc/x64/Release/*.exe
            server-mfc/x64/Release/*.sha256

  download_artifact:
    name: Download built artifacts
    runs-on: ubuntu-latest
    needs: build_server_mfc
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: server-mfc
          path: download/
      - run: ls download/
